### ISSUE TITLE
Can this be extended to existing atop raw metric files

### ISSUE THREAD

**Issue by danilansible** [rchakode/atop-graphite-grafana-monitoring#2]
Hi @rchakode 

Great work and thanks! for putting this together.
We collect atop metrics too from different servers and looking for a way to centralize viewing in grafana.
Does the script you have work for existing collected metrics too??

we collect default metrics with 30 sec intervals for 24 hours and keep last 7 days of files as below in cron daily
atop  -w atoplog_`hostname`_$(date) 30 2880

Any help is much appreciated

**Comment by rchakode** [comment]
Hi @danilansible ,
Using the `-r <filepath>` option of atop you can instruct atop to read from the input file instead of getting raw counters form the system. 

With that in mind, you can clone the repo and update the script accordingly. 
Then, if you want to contribute back, please fire a pull request.

Let me know if this helps.
Otherwise, if you want that this extension be made by us, let me know so we can arrange that.

Rodrigue

**Comment by rchakode** [comment]
Will close this issue without feedback.

**Comment by danilansible** [comment]
Thank you @rchakode
